### ISSUE TITLE
Import error in JuliaBox

### ISSUE THREAD

**Issue by iglesias** [blegat/RowEchelon.jl#11]
I am unsure whether this is the correct place to report this: I guess it could be a problem in RowEchelon, a problem in JuliaBox, a version incompatiliby issue, etc. So, feel free to point me in the right direction if not here.

After adding RowEchelon to the Registered Packages list in JuliaBox's Package Builder, and performing a successful build:

```
using RowEchelon
````

gives back

```
INFO: Recompiling stale cache file /mnt/juliabox/.julia/lib/v0.6/RowEchelon.ji for module RowEchelon.
WARNING: Module Compat with uuid 3606162812786658 is missing from the cache.
This may mean module Compat does not support precompilation but is imported by a module that does.
ERROR: LoadError: Declaring __precompile__(false) is not allowed in files that are being precompiled.
Stacktrace:
 [1] _require(::Symbol) at ./loading.jl:455
 [2] require(::Symbol) at ./loading.jl:405
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] anonymous at ./<missing>:2
while loading /mnt/juliabox/.julia/v0.6/RowEchelon/src/RowEchelon.jl, in expression starting on line 5

Failed to precompile RowEchelon to /mnt/juliabox/.julia/lib/v0.6/RowEchelon.ji.

Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:463
 [3] require(::Symbol) at ./loading.jl:405
```

A similar error occurs on using a different package (Erdos). Note that this error on using Erdos does not occur when RowEchelon is not part of the build.

Thanks in advance!

**Comment by blegat** [comment]
Try removing `~/.julia/lib/v0.6/RowEchelon.ji` and `~/.julia/lib/v0.6/Compat.ji`. If it doesn't work, try removing all files in `~/.julia/lib/v0.6`

**Comment by iglesias** [comment]
Thanks for getting back.

Removing them from where?

In JuliaBox, what I do is add the package to Registered Packages in JuliaBox's Package Builder and that's it.

**Comment by blegat** [comment]
Right, I forgot you were on JuliaBox. Then I have no idea, you might get more answer by posting this on [Discourse](https://discourse.julialang.org/c/tools) :)
