### ISSUE TITLE
Return the pivot vector?

### ISSUE THREAD

**Issue by PBrdng** [blegat/RowEchelon.jl#5]
Hi,

thank you very much for maintaining this function. 

I want to use it to compute a sparse basis for a kernel of a matrix. For this I would need the function to return the pivot vector with the positions of the 1 in each row (or, equivalently, the position of the non 0-1 column vectors). 

The question now is: Could you quickly modify the code so that is does this? Or, would it be ok for you, if I took the code and modified it myself (and providing it on my GitHub page)? 

Many thanks in advance, 
Paul

**Comment by blegat** [comment]
Hello, you are welcome to fork it as long as you keep the copyright notice as explained [here](https://github.com/blegat/RowEchelon.jl/blob/master/LICENSE.md).
If we want the change to be merged into this package, we need to make sure that it will not worsen the experience of users of `rref!` that do not need the pivot vector.
For this reason, it seems appropriate to create a new function (which would ideally share code with `rref!`) which returns the matrix and pivot vector.

**Comment by PB12345** [comment]
Ok, I will do that. Sure it makes sense to keep a function rref() without the pivot vector. I'm thinking about an optional argument to pass that makes the pivot vector available.

**Comment by blegat** [comment]
Having an optional argument is tricky because it will make the return type dependent on the value of the arguments which is not a good practice in Julia since it will make the compiler unable to infer the return type.

**Comment by PB12345** [comment]
Sorry I meant something different actually: Creating a new function, also called rref(), but that takes an additional input, say a boolean, and then depending on true or false returns the pivot or nor. Or is it better practice to give the new function a new name, say rref_pivot()?

**Comment by blegat** [comment]
If depending on the value of the boolean, you return the pivot or not then the return type will depends on the value of the boolean so this is type unstable.
Giving a new name seems simpler indeed.

**Comment by PB12345** [comment]
Hi, sorry for not replying for such a long time. I realised that I can use the original rref() for my needs by computing the kernel with svd and applying rref() to the result. Hence, I don't need the pivot anymore. You can close this issue or implement the pivot to your code; as its better for you. Thank you for taking care, though.

**Comment by blegat** [comment]
No worry, I am glad you found a solution :)

**Comment by blegat** [comment]
@PBrdng closed by #6 ?

**Comment by PBrdng** [comment]
yes
